# Generated by Django 5.2 on 2025-09-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_module_permission_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
