# Generated by Django 5.2 on 2025-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_national_id_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_root',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('مدير', 'مدير'), ('مستخدم', 'مستخدم')], default='مستخدم', max_length=20),
        ),
    ]
