# Generated by Django 5.2 on 2025-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_moderator_remove_user_is_root_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions', to='users.permission'),
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
