# Generated by Django 5.2 on 2025-09-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_permissions_delete_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('مدير', 'مدير'), ('مشرف', 'مشرف')], default='مشرف', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'اسم المستخدم موجود بالفعل'}, max_length=20, unique=True),
        ),
    ]
