# Generated by Django 5.2 on 2025-10-11 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال الاسم الكامل'}, max_length=150, verbose_name='الاسم الكامل رباعي')),
                ('national_id', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الهوية', 'unique': 'رقم الهوية مسجل مسبقاً'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'رقم الهوية يجب أن يتكون من 10 أرقام')], verbose_name='رقم الهوية الوطنية')),
                ('grade', models.CharField(error_messages={'blank': 'يرجى إدخال الصف الدراسي'}, max_length=50, verbose_name='الصف الدراسي')),
                ('birthdate', models.DateField(error_messages={'invalid': 'تاريخ الميلاد غير صالح'}, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], error_messages={'blank': 'يرجى تحديد الجنس'}, max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(choices=[('سعودي', 'سعودي'), ('غير سعودي', 'غير سعودي')], error_messages={'blank': 'يرجى تحديد الجنسية'}, max_length=20, verbose_name='الجنسية')),
                ('residence', models.CharField(error_messages={'blank': 'يرجى إدخال مكان الإقامة'}, max_length=100, verbose_name='مكان الإقامة الحالي')),
                ('region', models.CharField(error_messages={'blank': 'يرجى اختيار المنطقة'}, max_length=50, verbose_name='المنطقة الإدارية')),
                ('city', models.CharField(error_messages={'blank': 'يرجى اختيار المدينة'}, max_length=50, verbose_name='المدينة')),
                ('entity_type', models.CharField(choices=[('جمعيات تحفيظ القرآن الكريم بالمملكة', 'جمعيات تحفيظ القرآن الكريم بالمملكة'), ('مدارس تحفيظ القرآن الكريم', 'مدارس تحفيظ القرآن الكريم'), ('التعليم العام (الحكومي، الأهلي، الأجنبي)', 'التعليم العام (الحكومي، الأهلي، الأجنبي)')], error_messages={'blank': 'يرجى اختيار نوع الجهة'}, max_length=100, verbose_name='نوع الجهة')),
                ('entity_name', models.CharField(error_messages={'blank': 'يرجى كتابة اسم الجهة'}, max_length=150, verbose_name='اسم الجهة')),
                ('phone', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الجوال'}, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='البريد الإلكتروني غير صالح')], verbose_name='البريد الإلكتروني')),
                ('guardian_name', models.CharField(error_messages={'blank': 'يرجى إدخال اسم ولي الأمر الكامل'}, max_length=150, verbose_name='اسم ولي الأمر الكامل')),
                ('guardian_relation', models.CharField(error_messages={'blank': 'يرجى تحديد صلة القرابة'}, max_length=50, verbose_name='صلة القرابة')),
                ('guardian_phone', models.CharField(error_messages={'blank': 'يرجى إدخال رقم الجوال لولي الأمر'}, verbose_name='رقم جوال ولي الأمر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'متسابق',
                'verbose_name_plural': 'المتسابقون',
                'ordering': ['-created_at'],
            },
        ),
    ]
