# Generated by Django 5.2 on 2025-10-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'يرجى إدخال اسم المستوى.', 'unique': 'يوجد مستوى بهذا الاسم مسبقًا.'}, help_text='أدخل اسم المستوى باللغة العربية، مثل: المستوى الأول', max_length=100, unique=True, verbose_name='اسم المستوى')),
                ('weight', models.PositiveSmallIntegerField(error_messages={'invalid': 'يجب إدخال رقم صحيح.'}, help_text='رقم يُستخدم لترتيب المستويات (مثلاً 1، 2، 3)', verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'المستوى',
                'verbose_name_plural': 'المستويات',
                'ordering': ['weight'],
            },
        ),
    ]
