# Generated by Django 5.2 on 2025-10-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='applicants.level', verbose_name='المستوى'),
        ),
    ]
